### ISSUE TITLE
Is there a way to run this as docker container outside of hassio addons?

### ISSUE THREAD

**Issue by bryceoj** [joshgetter/hassio-addons#16]

**Comment by bryceoj** [comment]
Figured out the solution

**Comment by fabriph** [comment]
Would you mind sharing any specific steps that you followed? I'm only starting to get familiar with Docker.
Did you just cd to `kasa-camera ` and did something like `$ docker build` and `$ docker run`?

Thanks

**Comment by bryceoj** [comment]
I just used the published image on docker hub at joshgetter/amd64-addon-kasa-camera:latest

Youll need to map a path for /data/  that includes the config
