### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by britaliano** [joshgetter/hassio-addons#2]
Hello, thanks for this Add-In.

Trying to implement with a Kasa KC100 camera. In the log for the Add In, I get these messages (obfuscated where necessary):

[Controller] Controller is starting.
[Controller] Loading configuration.
[Controller] Initial toggle status: True.
[Wrapper] Starting Ffmpeg.
[Controller] Controller is running.
[HealthChecker] Starting health checker.
[https @ 0x7fa8224460] No trailing CRLF found in HTTP header. Adding it.
[tls @ 0x55ba39f9a0] Error in the pull function.
https://192.168.68.47:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd: I/O error
[HealthChecker] Error detected.
[Controller] Restarting Ffmpeg. Retry: 1.
[Wrapper] Restarting Ffmpeg.
[Wrapper] Killing Ffmpeg.
[HealthChecker] Stopping health checker.

My config file:

kasausername: [correct Kasa Username]
kasapassword: [correct Kasa Password]
cameraip: 192.168.68.47
cameraname: kitchencam
retrylimit: 5

Added to configuration.yaml:

camera:
  - platform: generic
    name: "Kitchen Camera"
    still_image_url: "http://192.168.68.47:43330/thumbnails/kitchencam.jpg"
    stream_source: "http://192.168.68.47:43330/hls/kitchencam.m3u8"

Have I messed up on the config?

**Comment by joshgetter** [comment]
@britaliano - I think your config looks fine. I actually get a similar error from time to time, I'm still looking for the cause of the problem. My current theory is that the camera will occasionally get I/O errors which messes with the stream. Generally the retries don't really help much because the camera will be stuck in a bad state. I'm looking for an actual solution, but in the meantime I'm thinking of adding a delay between retries to give the camera a chance to start the stream again.

**Comment by britaliano** [comment]
Thanks Josh. I have actually never had it working at all, it’s not intermittent. 

Having said that, grateful for the work you have done so far and fingers crossed that you find a solution. 

In another version of our universe, Tp Link actually allow users to use the tools they have paid for in the way they want to.

**Comment by joshgetter** [comment]
Appreciate the kind words. Actually after looking at your config a bit closer it looks like you have the camera ip entered in the configuration.yaml. That should actually be the home assistant host ip. 

So the configuration.yaml would be:

still_image_url: "http://<HA IP>:43330/thumbnails/kitchencam.jpg"
stream_source: "http://<HA IP>:43330/hls/kitchencam.m3u8"

I think the readme is wrong and shows the camera ip in the configuration.yaml so I’ll update that.

**Comment by britaliano** [comment]
It works with the change you suggested!

I see the still image, not the stream but I will work on that. 

Thanks again!
