### ISSUE TITLE
Is this integration still working?

### ISSUE THREAD

**Issue by geidorei** [joshgetter/hassio-addons#21]
Been a bit lazy past few months lol. Updating HA as theres a lot of changes....

My Kasa camera used to work but now is dead, also code as below, HA doesnt like at all.

#Kasa Camera
  platform: generic
  name: "Hallway Camera"
  still_image_url: "http://XXXX:43330/thumbnails/camera.hallwaycamera.jpg"
  stream_source: "http://XXXX:43330/hls/camera.hallwaycamera.m3u8"
 
Prob me again but just cant fig out. 

In log just says has become unavailable...

confused dot com.... Any ideas?

**Comment by impop** [comment]
Have you checked the add-on configuration itself? Has the camera changed the IP? is the password still valid? Is the add-on stopped for whatever reason? 

Attach logs.

Miquel

**Comment by geidorei** [comment]
I will do a double check....

**Comment by geidorei** [comment]
Hi Miguel

All ok, IP not changed. username and password also all ok.

I seam to be getting issues with the stream but cant find any solution. Log as follows directly after a restart:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Nginx
Nginx Started
Starting controller
Starting KasaStreamer
info: KasaStreamer.Camera[0]
      [HallwayCamera] Starting camera
info: System.Net.Http.HttpClient.KasaHttpClient.LogicalHandler[100]
      Start processing HTTP request GET https://192.168.1.82:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd
info: System.Net.Http.HttpClient.KasaHttpClient.ClientHandler[100]
      Sending HTTP request GET https://192.168.1.82:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
info: KasaStreamer.Ffmpeg[0]
      [HallwayCamera] Ffmpeg started
info: System.Net.Http.HttpClient.KasaHttpClient.ClientHandler[101]
      Received HTTP response headers after 907.2519ms - 401
info: System.Net.Http.HttpClient.KasaHttpClient.LogicalHandler[101]
      End processing HTTP request after 982.5623ms - 401
fail: KasaStreamer.KasaStreamReader[0]
      [HallwayCamera] An error occurred while reading camera stream.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (401 Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at KasaStreamer.KasaStreamReader.StartSplittingStream(CancellationToken cancellationToken) in /KasaStreamer/KasaStreamer/KasaStreamReader.cs:line 117
info: KasaStreamer.HealthChecker[0]
      [HallwayCamera] Starting health check
info: KasaStreamer.HealthChecker[0]
      [HallwayCamera] IS NOT healthy
info: KasaStreamer.Camera[0]
      [HallwayCamera] Stopping camera
info: KasaStreamer.Ffmpeg[0]
      [HallwayCamera] Ffmpeg stopped
info: KasaStreamer.Camera[0]
      [HallwayCamera] Starting camera
info: System.Net.Http.HttpClient.KasaHttpClient.LogicalHandler[100]
      Start processing HTTP request GET https://192.168.1.82:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd
info: System.Net.Http.HttpClient.KasaHttpClient.ClientHandler[100]
      Sending HTTP request GET https://192.168.1.82:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd
info: KasaStreamer.Ffmpeg[0]
      [HallwayCamera] Ffmpeg started
info: System.Net.Http.HttpClient.KasaHttpClient.ClientHandler[101]
      Received HTTP response headers after 228.2653ms - 401
info: System.Net.Http.HttpClient.KasaHttpClient.LogicalHandler[101]
      End processing HTTP request after 228.8362ms - 401
fail: KasaStreamer.KasaStreamReader[0]
      [HallwayCamera] An error occurred while reading camera stream.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (401 Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at KasaStreamer.KasaStreamReader.StartSplittingStream(CancellationToken cancellationToken) in /KasaStreamer/KasaStreamer/KasaStreamReader.cs:line 117


Main log:
2023-07-04 11:33:45.526 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.hallway_camera] Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) 

Thanks for you help.

**Comment by geidorei** [comment]
Fixed it - lol. Deleted the integration again, restarted HA, and it now works.... No idea why. Hey ho, it's working and that's what matters. Many thanks.
