### ISSUE TITLE
audio support?

### ISSUE THREAD

**Issue by angadsingh** [joshgetter/hassio-addons#4]
any chance getting audio support to work on this? sucks having to ultimately go to the kasa app again to download a clip (if it detected motion!) for the audio

**Comment by deanlongstaff** [comment]
+1 - I've been waiting months for audio support on this. Unfortunately, i am missing critical evidence of criminal damage as the audio is missing now :(

**Comment by joshgetter** [comment]
Audio support was just added with the 2.0 release. This involved a re-write of the application, so I would recommend backing up the addon/home assistant prior to upgrading just to be safe. Also now that the application is processing audio in addition to video I have noticed that the CPU usage is higher, which may be a concern if you're running something like a Raspberry Pi. As a note I'm running an Intel NUC with two cameras and it's using about 50% CPU.
