### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by geidorei** [joshgetter/hassio-addons#5]
However, I am probably doing something wrong?

I presume the following goes into configuration.yaml (obviously changed to my details)? If so all I get is errors?

kasausername: user@example.com
kasapassword: password1234
cameras:
  - cameraname: livingroom
    cameraip: 192.168.1.3
  - cameraname: kitchen
    cameraip: 192.168.1.2
retrylimit: 5
retrysleep: 30
toggleentity: input_boolean.kasa_camera_enabled

The errors:
Component error: toggleentity - Integration 'toggleentity' not found.
Component error: retrysleep - Integration 'retrysleep' not found.
Component error: kasausername - Integration 'kasausername' not found.
Component error: kasapassword - Integration 'kasapassword' not found.
Component error: retrylimit - Integration 'retrylimit' not found.
Component error: cameras - Integration 'cameras' not f

I have put the kasa-camera directory in 'custom components', again is this right?

Thanking you in advance for your help.

**Comment by r1ch** [comment]
@geidorei this doesn't go in configuration.yaml - you need to add this into the configuration of the add-on itself

On my installation I click Supervisor>Kasa Camera>Configuration (it's at the top of the screen)

**Comment by r1ch** [comment]
Once you've done that (and started the add-on) try opening a browser window and going to:

http://_<HA IP>_:43330/hls/_<Camera Name>_.m3u8

Replace _<HA IP>_ with your ip address, or "homeassistant.local" and
_<Camera Name>_ with the name of the camera

In your configuration YAML you can add the following - this makes HA aware of the cameras

(change livingroom / kitchen to match your names) 

camera:
  - platform: generic
    name: "Living Room Camera"
    still_image_url: "http://<HA IP>:43330/thumbnails/livingroom.jpg"
    stream_source: "http://<HA IP>:43330/hls/livingroom.m3u8"
  - platform: generic
    name: "Kitchen Camera"
    still_image_url: "http://<HA IP>:43330/thumbnails/kitchen.jpg"
    stream_source: "http://<HA IP>:43330/hls/kitchen.m3u8"

**Comment by geidorei** [comment]
Thanks folks i will have a go this week, and post back if i succeed. Lol

**Comment by geidorei** [comment]
Hi - only just back to this....

Supervisor>Kasa Camera>Configuration - under Supervisor Kasa Camera isn't showing???

**Comment by geidorei** [comment]
Sussed it lol - however no joy... I am using a KC115 though and no luck...

**Comment by geidorei** [comment]
My bad - No idea why but it is working now....
